/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package edu.upenn.gloDB.parser;

public interface ParserConstants {

  int EOF = 0;
  int SP0 = 6;
  int SP1 = 7;
  int EQUALS = 8;
  int SEPARATOR = 9;
  int INTEGER = 10;
  int nINTEGER = 11;
  int lLENGTH = 12;
  int lLENGTH2 = 13;
  int rLENGTH = 14;
  int LENGTH = 15;
  int FROM = 16;
  int lREPEAT = 17;
  int rREPEAT = 18;
  int lGROUP = 19;
  int rGROUP = 20;
  int lSET = 21;
  int rSET = 22;
  int IGNORE = 23;
  int POS = 24;
  int AND = 25;
  int sAND = 26;
  int OR = 27;
  int MINUS = 28;
  int sMINUS = 29;
  int bAND = 30;
  int bOR = 31;
  int bMINUS = 32;
  int bNOT = 33;
  int HOOK = 34;
  int PLUS = 35;
  int STAR = 36;
  int EOL = 37;
  int WITHIN = 38;
  int TIMES = 39;
  int REPEATED = 40;
  int POSITIONS = 41;
  int allTRACKS = 42;
  int OBJECT = 43;
  int ASSIGN = 44;
  int TRACK = 45;
  int SEQUENCE = 46;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"then\"",
    "\"followed by\"",
    "\"\\r\"",
    "\"\\t\"",
    "<SP0>",
    "<SP1>",
    "\"=\"",
    "\",\"",
    "<INTEGER>",
    "<nINTEGER>",
    "\"<\"",
    "<lLENGTH2>",
    "\">\"",
    "<LENGTH>",
    "<FROM>",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"~\"",
    "\"POS\"",
    "\"AND\"",
    "\"sAND\"",
    "\"OR\"",
    "\"MINUS\"",
    "\"sMINUS\"",
    "\"&&\"",
    "\"||\"",
    "\"-\"",
    "\"!\"",
    "\"?\"",
    "\"+\"",
    "\"*\"",
    "\"\\n\"",
    "\"within\"",
    "\"times\"",
    "\"repeated\"",
    "\"positions\"",
    "<allTRACKS>",
    "<OBJECT>",
    "<ASSIGN>",
    "<TRACK>",
    "<SEQUENCE>",
    "\";\"",
  };

}
