/* Generated By:JavaCC: Do not edit this line. ParserTokenManager.java */
package edu.upenn.gloDB.parser;
import edu.upenn.gloDB.*;
import java.io.StringReader;
import java.util.HashMap;
import java.util.HashSet;
import java.util.ArrayList;
import java.util.Iterator;

public class ParserTokenManager implements ParserConstants
{
  public  java.io.PrintStream debugStream = System.out;
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x100000000L) != 0L)
            return 2;
         if ((active0 & 0x24000000L) != 0L)
         {
            jjmatchedKind = 43;
            return 22;
         }
         if ((active0 & 0x3c011000004L) != 0L)
         {
            jjmatchedKind = 43;
            return 99;
         }
         if ((active0 & 0x8L) != 0L)
         {
            jjmatchedKind = 43;
            return 30;
         }
         if ((active0 & 0x1000L) != 0L)
            return 100;
         if ((active0 & 0x8000000L) != 0L)
         {
            jjmatchedKind = 43;
            return 19;
         }
         if ((active0 & 0x2000000L) != 0L)
         {
            jjmatchedKind = 43;
            return 75;
         }
         return -1;
      case 1:
         if ((active0 & 0x3c03700000cL) != 0L)
         {
            jjmatchedKind = 43;
            jjmatchedPos = 1;
            return 99;
         }
         if ((active0 & 0x8000000L) != 0L)
            return 99;
         return -1;
      case 2:
         if ((active0 & 0x3000000L) != 0L)
            return 99;
         if ((active0 & 0x3c03400000cL) != 0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 43;
               jjmatchedPos = 2;
            }
            return 99;
         }
         return -1;
      case 3:
         if ((active0 & 0x3c030000008L) != 0L)
         {
            jjmatchedKind = 43;
            jjmatchedPos = 3;
            return 99;
         }
         if ((active0 & 0x4000004L) != 0L)
            return 99;
         return -1;
      case 4:
         if ((active0 & 0x34020000008L) != 0L)
         {
            jjmatchedKind = 43;
            jjmatchedPos = 4;
            return 99;
         }
         if ((active0 & 0x8010000000L) != 0L)
            return 99;
         return -1;
      case 5:
         if ((active0 & 0x4020000000L) != 0L)
            return 99;
         if ((active0 & 0x30000000008L) != 0L)
         {
            jjmatchedKind = 43;
            jjmatchedPos = 5;
            return 99;
         }
         return -1;
      case 6:
         if ((active0 & 0x30000000008L) != 0L)
         {
            jjmatchedKind = 43;
            jjmatchedPos = 6;
            return 99;
         }
         return -1;
      case 7:
         if ((active0 & 0x20000000008L) != 0L)
         {
            jjmatchedKind = 43;
            jjmatchedPos = 7;
            return 99;
         }
         if ((active0 & 0x10000000000L) != 0L)
            return 99;
         return -1;
      case 8:
         if ((active0 & 0x8L) != 0L)
         {
            if (jjmatchedPos < 7)
            {
               jjmatchedKind = 43;
               jjmatchedPos = 7;
            }
            return 101;
         }
         if ((active0 & 0x20000000000L) != 0L)
            return 99;
         return -1;
      case 9:
         if ((active0 & 0x8L) != 0L)
         {
            if (jjmatchedPos < 7)
            {
               jjmatchedKind = 43;
               jjmatchedPos = 7;
            }
            return -1;
         }
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
private final int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private final int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
private final int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 10:
         return jjStopAtPos(0, 37);
      case 33:
         return jjStopAtPos(0, 33);
      case 38:
         return jjMoveStringLiteralDfa1_0(0x40000000L);
      case 40:
         return jjStopAtPos(0, 19);
      case 41:
         return jjStopAtPos(0, 20);
      case 42:
         return jjStopAtPos(0, 36);
      case 43:
         return jjStopAtPos(0, 35);
      case 44:
         return jjStopAtPos(0, 9);
      case 45:
         return jjStartNfaWithStates_0(0, 32, 2);
      case 59:
         return jjStopAtPos(0, 47);
      case 60:
         return jjStartNfaWithStates_0(0, 12, 100);
      case 61:
         return jjStopAtPos(0, 8);
      case 62:
         return jjStopAtPos(0, 14);
      case 63:
         return jjStopAtPos(0, 34);
      case 91:
         return jjStopAtPos(0, 21);
      case 93:
         return jjStopAtPos(0, 22);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa1_0(0x2000000L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa1_0(0x8L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa1_0(0x10000000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa1_0(0x8000000L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa1_0(0x20001000000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa1_0(0x10000000000L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa1_0(0x24000000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa1_0(0x8000000004L);
      case 87:
      case 119:
         return jjMoveStringLiteralDfa1_0(0x4000000000L);
      case 123:
         return jjStopAtPos(0, 17);
      case 124:
         return jjMoveStringLiteralDfa1_0(0x80000000L);
      case 125:
         return jjStopAtPos(0, 18);
      case 126:
         return jjStopAtPos(0, 23);
      default :
         return jjMoveNfa_0(1, 0);
   }
}
private final int jjMoveStringLiteralDfa1_0(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 38:
         if ((active0 & 0x40000000L) != 0L)
            return jjStopAtPos(1, 30);
         break;
      case 65:
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x4000000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x10000000000L);
      case 72:
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0x4L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0xc010000000L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa2_0(active0, 0x20000000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0x2000000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa2_0(active0, 0x20001000008L);
      case 82:
      case 114:
         if ((active0 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(1, 27, 99);
         break;
      case 124:
         if ((active0 & 0x80000000L) != 0L)
            return jjStopAtPos(1, 31);
         break;
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
private final int jjMoveStringLiteralDfa2_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 68:
      case 100:
         if ((active0 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(2, 25, 99);
         break;
      case 69:
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x4L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x20000000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x8L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000000000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x14000000L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa3_0(active0, 0x10000000000L);
      case 83:
      case 115:
         if ((active0 & 0x1000000L) != 0L)
         {
            jjmatchedKind = 24;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x20000000000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000000000L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
private final int jjMoveStringLiteralDfa3_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 68:
      case 100:
         if ((active0 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(3, 26, 99);
         break;
      case 69:
      case 101:
         return jjMoveStringLiteralDfa4_0(active0, 0x18000000000L);
      case 72:
      case 104:
         return jjMoveStringLiteralDfa4_0(active0, 0x4000000000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x20000000000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa4_0(active0, 0x8L);
      case 78:
      case 110:
         if ((active0 & 0x4L) != 0L)
            return jjStartNfaWithStates_0(3, 2, 99);
         return jjMoveStringLiteralDfa4_0(active0, 0x20000000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x10000000L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
private final int jjMoveStringLiteralDfa4_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0x10000000000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x4000000000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa5_0(active0, 0x8L);
      case 83:
      case 115:
         if ((active0 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(4, 28, 99);
         else if ((active0 & 0x8000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 39, 99);
         break;
      case 84:
      case 116:
         return jjMoveStringLiteralDfa5_0(active0, 0x20000000000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0x20000000L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
private final int jjMoveStringLiteralDfa5_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 73:
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0x20000000000L);
      case 78:
      case 110:
         if ((active0 & 0x4000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 38, 99);
         break;
      case 83:
      case 115:
         if ((active0 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(5, 29, 99);
         break;
      case 84:
      case 116:
         return jjMoveStringLiteralDfa6_0(active0, 0x10000000000L);
      case 87:
      case 119:
         return jjMoveStringLiteralDfa6_0(active0, 0x8L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0);
}
private final int jjMoveStringLiteralDfa6_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0);
      return 6;
   }
   switch(curChar)
   {
      case 69:
      case 101:
         return jjMoveStringLiteralDfa7_0(active0, 0x10000000008L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa7_0(active0, 0x20000000000L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0);
}
private final int jjMoveStringLiteralDfa7_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0);
      return 7;
   }
   switch(curChar)
   {
      case 68:
      case 100:
         if ((active0 & 0x10000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 40, 99);
         return jjMoveStringLiteralDfa8_0(active0, 0x8L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa8_0(active0, 0x20000000000L);
      default :
         break;
   }
   return jjStartNfa_0(6, active0);
}
private final int jjMoveStringLiteralDfa8_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0);
      return 8;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa9_0(active0, 0x8L);
      case 83:
      case 115:
         if ((active0 & 0x20000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 41, 99);
         break;
      default :
         break;
   }
   return jjStartNfa_0(7, active0);
}
private final int jjMoveStringLiteralDfa9_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0);
      return 9;
   }
   switch(curChar)
   {
      case 66:
      case 98:
         return jjMoveStringLiteralDfa10_0(active0, 0x8L);
      default :
         break;
   }
   return jjStartNfa_0(8, active0);
}
private final int jjMoveStringLiteralDfa10_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(8, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0);
      return 10;
   }
   switch(curChar)
   {
      case 89:
      case 121:
         if ((active0 & 0x8L) != 0L)
            return jjStopAtPos(10, 3);
         break;
      default :
         break;
   }
   return jjStartNfa_0(9, active0);
}
private final void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private final void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private final void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}
private final void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}
private final void jjCheckNAddStates(int start)
{
   jjCheckNAdd(jjnextStates[start]);
   jjCheckNAdd(jjnextStates[start + 1]);
}
private final int jjMoveNfa_0(int startState, int curPos)
{
   int[] nextStates;
   int startsAt = 0;
   jjnewStateCnt = 99;
   int i = 1;
   jjstateSet[0] = startState;
   int j, kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 30:
                  if ((0x3ff200000000000L & l) != 0L)
                     jjCheckNAddStates(0, 2);
                  else if (curChar == 61)
                  {
                     if (kind > 44)
                        kind = 44;
                  }
                  else if (curChar == 32)
                     jjCheckNAddTwoStates(97, 98);
                  if ((0x3ff200000000000L & l) != 0L)
                  {
                     if (kind > 43)
                        kind = 43;
                     jjCheckNAdd(95);
                  }
                  break;
               case 101:
                  if (curChar == 61)
                  {
                     if (kind > 44)
                        kind = 44;
                  }
                  else if (curChar == 32)
                     jjCheckNAddTwoStates(97, 98);
                  break;
               case 100:
                  if (curChar == 59)
                  {
                     if (kind > 13)
                        kind = 13;
                  }
                  else if (curChar == 32)
                     jjCheckNAddTwoStates(4, 5);
                  break;
               case 75:
                  if ((0x3ff200000000000L & l) != 0L)
                     jjCheckNAddStates(0, 2);
                  else if (curChar == 32)
                     jjstateSet[jjnewStateCnt++] = 92;
                  else if (curChar == 61)
                  {
                     if (kind > 44)
                        kind = 44;
                  }
                  if ((0x3ff200000000000L & l) != 0L)
                  {
                     if (kind > 43)
                        kind = 43;
                     jjCheckNAdd(95);
                  }
                  else if (curChar == 32)
                     jjCheckNAddTwoStates(97, 98);
                  if (curChar == 32)
                     jjstateSet[jjnewStateCnt++] = 74;
                  break;
               case 19:
                  if ((0x3ff200000000000L & l) != 0L)
                     jjCheckNAddStates(0, 2);
                  else if (curChar == 61)
                  {
                     if (kind > 44)
                        kind = 44;
                  }
                  else if (curChar == 32)
                     jjCheckNAddTwoStates(97, 98);
                  if ((0x3ff200000000000L & l) != 0L)
                  {
                     if (kind > 43)
                        kind = 43;
                     jjCheckNAdd(95);
                  }
                  break;
               case 22:
                  if ((0x3ff200000000000L & l) != 0L)
                     jjCheckNAddStates(0, 2);
                  else if (curChar == 58)
                  {
                     if (kind > 46)
                        kind = 46;
                     jjCheckNAdd(23);
                  }
                  else if (curChar == 61)
                  {
                     if (kind > 44)
                        kind = 44;
                  }
                  else if (curChar == 32)
                     jjCheckNAddTwoStates(97, 98);
                  if ((0x3ff200000000000L & l) != 0L)
                  {
                     if (kind > 43)
                        kind = 43;
                     jjCheckNAdd(95);
                  }
                  break;
               case 99:
                  if ((0x3ff200000000000L & l) != 0L)
                     jjCheckNAddStates(0, 2);
                  else if (curChar == 61)
                  {
                     if (kind > 44)
                        kind = 44;
                  }
                  else if (curChar == 32)
                     jjCheckNAddTwoStates(97, 98);
                  if ((0x3ff200000000000L & l) != 0L)
                  {
                     if (kind > 43)
                        kind = 43;
                     jjCheckNAdd(95);
                  }
                  break;
               case 1:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 10)
                        kind = 10;
                     jjCheckNAdd(0);
                  }
                  else if (curChar == 60)
                     jjCheckNAddTwoStates(4, 5);
                  else if (curChar == 45)
                     jjCheckNAdd(2);
                  break;
               case 0:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 10)
                     kind = 10;
                  jjCheckNAdd(0);
                  break;
               case 2:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 11)
                     kind = 11;
                  jjCheckNAdd(2);
                  break;
               case 3:
                  if (curChar == 60)
                     jjCheckNAddTwoStates(4, 5);
                  break;
               case 4:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(4, 5);
                  break;
               case 5:
                  if (curChar == 59)
                     kind = 13;
                  break;
               case 10:
                  if (curChar != 32)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 18:
                  if (curChar == 32)
                     jjstateSet[jjnewStateCnt++] = 17;
                  break;
               case 23:
                  if (curChar != 32)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAdd(23);
                  break;
               case 25:
                  if (curChar != 32)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjstateSet[jjnewStateCnt++] = 25;
                  break;
               case 39:
                  if (curChar == 32)
                     jjstateSet[jjnewStateCnt++] = 38;
                  break;
               case 48:
                  if (curChar == 32)
                     jjstateSet[jjnewStateCnt++] = 47;
                  break;
               case 60:
                  if (curChar == 32)
                     jjstateSet[jjnewStateCnt++] = 59;
                  break;
               case 64:
                  if (curChar == 32)
                     jjstateSet[jjnewStateCnt++] = 63;
                  break;
               case 67:
                  if (curChar == 32)
                     jjstateSet[jjnewStateCnt++] = 66;
                  break;
               case 77:
                  if (curChar != 32)
                     break;
                  if (kind > 45)
                     kind = 45;
                  jjstateSet[jjnewStateCnt++] = 77;
                  break;
               case 82:
                  if (curChar == 32)
                     jjstateSet[jjnewStateCnt++] = 81;
                  break;
               case 85:
                  if (curChar == 32)
                     jjstateSet[jjnewStateCnt++] = 84;
                  break;
               case 93:
                  if (curChar == 32)
                     jjstateSet[jjnewStateCnt++] = 92;
                  break;
               case 95:
                  if ((0x3ff200000000000L & l) == 0L)
                     break;
                  if (kind > 43)
                     kind = 43;
                  jjCheckNAdd(95);
                  break;
               case 96:
                  if ((0x3ff200000000000L & l) != 0L)
                     jjCheckNAddStates(0, 2);
                  break;
               case 97:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(97, 98);
                  break;
               case 98:
                  if (curChar == 61)
                     kind = 44;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 30:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(0, 2);
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 43)
                        kind = 43;
                     jjCheckNAdd(95);
                  }
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 41;
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 29;
                  break;
               case 75:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(0, 2);
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 43)
                        kind = 43;
                     jjCheckNAdd(95);
                  }
                  break;
               case 19:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(0, 2);
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 43)
                        kind = 43;
                     jjCheckNAdd(95);
                  }
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 18;
                  break;
               case 22:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(0, 2);
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 43)
                        kind = 43;
                     jjCheckNAdd(95);
                  }
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 24;
                  break;
               case 99:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(0, 2);
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 43)
                        kind = 43;
                     jjCheckNAdd(95);
                  }
                  break;
               case 1:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 43)
                        kind = 43;
                     jjCheckNAddStates(3, 6);
                  }
                  if ((0x200000002L & l) != 0L)
                     jjAddStates(7, 8);
                  else if ((0x100000001000L & l) != 0L)
                     jjAddStates(9, 10);
                  else if ((0x4000000040L & l) != 0L)
                     jjAddStates(11, 12);
                  else if ((0x8000000080000L & l) != 0L)
                     jjAddStates(13, 14);
                  else if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 19;
                  else if (curChar == 95)
                     jjstateSet[jjnewStateCnt++] = 7;
                  break;
               case 6:
                  if ((0x10000000100000L & l) != 0L && kind > 42)
                     kind = 42;
                  break;
               case 7:
                  if (curChar == 95)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 8:
                  if (curChar == 95)
                     jjstateSet[jjnewStateCnt++] = 7;
                  break;
               case 9:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 11:
                  if ((0x800000008L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 9;
                  break;
               case 12:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 11;
                  break;
               case 13:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 12;
                  break;
               case 14:
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 13;
                  break;
               case 15:
                  if ((0x2000000020000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 14;
                  break;
               case 16:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 15;
                  break;
               case 17:
                  if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 16;
                  break;
               case 20:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 19;
                  break;
               case 21:
                  if ((0x8000000080000L & l) != 0L)
                     jjAddStates(13, 14);
                  break;
               case 24:
                  if ((0x2000000020000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 25;
                  break;
               case 26:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 24;
                  break;
               case 27:
                  if ((0x4000000040L & l) != 0L)
                     jjAddStates(11, 12);
                  break;
               case 28:
                  if ((0x200000002000L & l) != 0L && kind > 16)
                     kind = 16;
                  break;
               case 29:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 28;
                  break;
               case 31:
                  if ((0x400000004000L & l) != 0L && kind > 16)
                     kind = 16;
                  break;
               case 32:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 31;
                  break;
               case 33:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 32;
                  break;
               case 34:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 33;
                  break;
               case 35:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 34;
                  break;
               case 36:
                  if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 35;
                  break;
               case 37:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 36;
                  break;
               case 38:
                  if ((0x1000000010000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 37;
                  break;
               case 40:
                  if ((0x200000002000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 39;
                  break;
               case 41:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 40;
                  break;
               case 42:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 41;
                  break;
               case 43:
                  if ((0x100000001000L & l) != 0L)
                     jjAddStates(9, 10);
                  break;
               case 44:
                  if ((0x400000004000L & l) != 0L && kind > 15)
                     kind = 15;
                  break;
               case 45:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 44;
                  break;
               case 46:
                  if ((0x4000000040L & l) != 0L && kind > 15)
                     kind = 15;
                  break;
               case 47:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 46;
                  break;
               case 49:
                  if ((0x10000000100L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 48;
                  break;
               case 50:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 49;
                  break;
               case 51:
                  if ((0x8000000080L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 50;
                  break;
               case 52:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 51;
                  break;
               case 53:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 52;
                  break;
               case 54:
                  if ((0x200000002L & l) != 0L)
                     jjAddStates(7, 8);
                  break;
               case 55:
                  if ((0x80000000800L & l) != 0L && kind > 42)
                     kind = 42;
                  break;
               case 56:
                  if ((0x800000008L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 55;
                  break;
               case 57:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 56;
                  break;
               case 58:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 57;
                  break;
               case 59:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 58;
                  break;
               case 61:
                  if ((0x200000002000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 60;
                  break;
               case 62:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 61;
                  break;
               case 63:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 62;
                  break;
               case 65:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 64;
                  break;
               case 66:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 65;
                  break;
               case 68:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 67;
                  break;
               case 69:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 68;
                  break;
               case 70:
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 69;
                  break;
               case 71:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 70;
                  break;
               case 72:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 71;
                  break;
               case 73:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 72;
                  break;
               case 74:
                  if ((0x4000000040L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 73;
                  break;
               case 76:
                  if ((0x80000000800L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 77;
                  break;
               case 78:
                  if ((0x800000008L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 76;
                  break;
               case 79:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 78;
                  break;
               case 80:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 79;
                  break;
               case 81:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 80;
                  break;
               case 83:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 82;
                  break;
               case 84:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 83;
                  break;
               case 86:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 85;
                  break;
               case 87:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 86;
                  break;
               case 88:
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 87;
                  break;
               case 89:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 88;
                  break;
               case 90:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 89;
                  break;
               case 91:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 90;
                  break;
               case 92:
                  if ((0x4000000040L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 91;
                  break;
               case 94:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 43)
                     kind = 43;
                  jjCheckNAddStates(3, 6);
                  break;
               case 95:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 43)
                     kind = 43;
                  jjCheckNAdd(95);
                  break;
               case 96:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(0, 2);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 99 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   96, 97, 98, 95, 96, 97, 98, 75, 93, 45, 53, 30, 42, 22, 26, 
};
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, "\75", "\54", null, null, "\74", 
null, "\76", null, null, "\173", "\175", "\50", "\51", "\133", "\135", "\176", null, 
null, null, null, null, null, "\46\46", "\174\174", "\55", "\41", "\77", "\53", 
"\52", "\12", null, null, null, null, null, null, null, null, null, "\73", };
public static final String[] lexStateNames = {
   "DEFAULT", 
};
static final long[] jjtoToken = {
   0xffffffffff01L, 
};
static final long[] jjtoSkip = {
   0x3eL, 
};
protected SimpleCharStream input_stream;
private final int[] jjrounds = new int[99];
private final int[] jjstateSet = new int[198];
protected char curChar;
public ParserTokenManager(SimpleCharStream stream)
{
   if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}
public ParserTokenManager(SimpleCharStream stream, int lexState)
{
   this(stream);
   SwitchTo(lexState);
}
public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private final void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 99; i-- > 0;)
      jjrounds[i] = 0x80000000;
}
public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}
public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   Token t = Token.newToken(jjmatchedKind);
   t.kind = jjmatchedKind;
   String im = jjstrLiteralImages[jjmatchedKind];
   t.image = (im == null) ? input_stream.GetImage() : im;
   t.beginLine = input_stream.getBeginLine();
   t.beginColumn = input_stream.getBeginColumn();
   t.endLine = input_stream.getEndLine();
   t.endColumn = input_stream.getEndColumn();
   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

public Token getNextToken() 
{
  int kind;
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {   
   try   
   {     
      curChar = input_stream.BeginToken();
   }     
   catch(java.io.IOException e)
   {        
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100002200L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

}
